version: '3.7'
services:
    api:
        container_name: api
        build: 
            context: app
            dockerfile: Dockerfile
        ports: 
            - "5000"
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - fullstack-postgres
        networks:
            - frontend
            - backend

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
            PGADMIN_DEFAULT_PASSWORD: "temporary"
        ports:
            - "5050:80"
        restart: unless-stopped
        networks:
            - backend
        depends_on:
            - fullstack-postgres

    fullstack-postgres:
        image: postgres
        container_name: postgres_container
        restart: always
        environment:
            - POSTGRES_USER="postgres"
            - POSTGRES_PASSWORD="postgres"
            - POSTGRES_DB="postgres"
            - DATABASE_HOST="localhost"
        ports:
            - '5432:5432'
        volumes:
            - database_postgres:/var/lib/postgresql/data
        networks:
            - backend

    webserver:
        image: nginx:latest
        container_name: webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        networks:
            - frontend            

# Networks to be created to facilitate communication between containers
networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    database_postgres:
    nginxdata:
        driver: local     